### ISSUE TITLE
Stopped working with latest update

### ISSUE THREAD

**Issue by Nijomi** [ST-Apps/CS-ParallelRoadTool#76] opened 2020-02-24 00:32 UTC
The tool has ceased to work with the latest update today.

**Comment by Marquillotuca89** [comment] 2020-03-03 04:23
I don't think we'll be getting an update. It's such a shame!

**Comment by ST-Apps** [comment] 2020-04-12 17:15
I'm considering getting back to actively develop this one actually.
I did a quick test and it worked for me, do you have more details on this issue?

**Comment by Marquillotuca89** [comment] 2020-04-12 17:21
> I'm considering getting back to actively develop this one actually.
> I did a quick test and it worked for me, do you have more details on this issue?

Well, for me, what happens is that sometimes, the tool just stops working. For example:  I'm building a highway, I toggle the tool on/off several times and randomly, the icon just stops showing and after that, I can't toggle on the tool again even with Ctrl +P. 
A lot of people are reporting similar bugs on Steam Workshop.

**Comment by Marquillotuca89** [comment] 2020-04-12 21:31
Today, I experimented the bug. I'm uploading the output log. 

[output_log.zip](https://github.com/ST-Apps/CS-ParallelRoadTool/files/4467185/output_log.zip)

**Comment by ST-Apps** [comment] 2020-04-17 15:35
Duplicate of #69

**Closed by ST-Apps** 2020-04-17 15:35 UTC
