### ISSUE TITLE
Incompatible with Network Skins after the last update

### ISSUE THREAD

**Issue by kaminogi** [ST-Apps/CS-ParallelRoadTool#19] opened 2018-06-09 07:57 UTC
I found I can't change "Street Lights" today.
Yesterday I was able to change.

Then I thought there was something to do with ParallelRoadTool's update, I deactivated once. Then Network Skins works normally.

In this session, I haven't opened ParallelRoadTool's window and not used.

Could you check the recent changes around road props?

**Comment by ST-Apps** [comment] 2018-06-09 08:28
Duplicate of #12

**Closed by ST-Apps** 2018-06-09 08:28 UTC
Labels: duplicate
