### ISSUE TITLE
It is possible to build outside of tile

### ISSUE THREAD

**Issue by pkej** [ST-Apps/CS-ParallelRoadTool#21] opened 2018-06-09 10:04 UTC
If I make a particularly wide network it is possible to build [outside the current tile by placing the network down along the boundary](https://steamcommunity.com/sharedfiles/filedetails/?id=1406837391). Only the "guide" road will be forbidden from plopping outside of the tile.

**Comment by DaEgi01** [comment] 2018-06-10 09:52
What is your expected behaviour? 
a) that placement of the "guide" road should be forbidden
b) PRT places only the roads until that would fit inside the boundaries

**Comment by pkej** [comment] 2018-06-11 09:54
For me a). If I've taken the time to make a stack I'm interested in using it as it is, and not truncated.

**Comment by DaEgi01** [comment] 2018-06-11 15:08
same for me, I would also prefer solution a)

**Comment by ST-Apps** [comment] 2018-06-11 17:31
Doing a) will break compatibility with FineRoadAnarchy, I'm sorry.

**Comment by DaEgi01** [comment] 2018-06-11 17:51
how about b) than? ;)
Users that don't use mods like "81 tiles" or "cross the line" will be in a world of pain otherwise.

**Comment by ST-Apps** [comment] 2018-06-11 17:53
b) doesn't make sense for the reasons that @pkej gave before.

**Comment by DaEgi01** [comment] 2018-06-11 18:00
I'm not sure @pkej would agree. 
IMO "a > b > current situation"

**Comment by ST-Apps** [comment] 2018-06-11 19:29
How is truncating half of a road better than drawing it outside the borders? :)

**Comment by DaEgi01** [comment] 2018-06-11 19:34
Its better because you don't get the user into a situation where he/she can't undo the previous action or further edit what was placed by PRT.

**Comment by pkej** [comment] 2018-06-19 08:33
I noticed other tools, like the terraforming tools, go outside the active tile. Therefore I believe it isn't a problem keeping the behavior as is. It's better all tools have the same behavior, and not spend time and resources on making it behave much differently than other tools :)

**Closed** 2018-06-28 17:35 UTC
Labels: dev, enhancement, wontfix
